### PR TITLE
Allow for custom max password length in 'Version'

### PR DESCRIPTION
**Pull request by patrickfav**
refs #22

### CODE REVIEW

**Comment by Indigo744** [comment]
Hello,

After playing with it a bit, I have some question.

Why does the `Verifier` needs a `Version`? It should be able to infer it from the hash (`$2y$`, `$2a$`...).
The version should only be needed for `VerifyStrict` if one wants to explicitly restrain the version allowed.

I think the length for the TruncateStrategy should not be tied to the Version. It should be independent.

What do you think?

**Comment by patrickfav** [comment]
> Why does the Verifier needs a Version?
Thats a good point. The problem is that the version identifier is not unique in my lib anymore. I will think about it

> I think the length for the TruncateStrategy should not be tied to the Version. It should be independent.

They are independent, they are just using it as configuration by default, which makes sense (why would you want a differnt lenght for those 2 properties?)

**Comment by Indigo744** [comment]
> They are independent, they are just using it as configuration by default, which makes sense (why would you want a differnt lenght for those 2 properties?)

I don't understand this sentence, sorry.

Correct me if I'm wrong, but now the LongPasswordStrategies interface expects a `Version` parameter, and nothing else. 
In **LongPasswordStrategies.java**:
```java
   public static LongPasswordStrategy truncate(BCrypt.Version version) {
        return new LongPasswordStrategy.TruncateStrategy(Objects.requireNonNull(version).allowedMaxPwLength);
    }
    public static LongPasswordStrategy hashSha512(BCrypt.Version version) {
        return new LongPasswordStrategy.Sha512DerivationStrategy(Objects.requireNonNull(version).allowedMaxPwLength);
    }
```

`LongPasswordStrategies.truncate()` should expects a length.
`LongPasswordStrategies.hashSha512()` should expects... nothing really. This strategy is supposed to allow user to stop caring about password length.

**Comment by patrickfav** [comment]
> Correct me if I'm wrong, but now the LongPasswordStrategies interface expects a Version parameter, and nothing else.

Ah yes, you are absoletly right - to me it makes the most sense

**Comment by Indigo744** [comment]
Ah, I can see your point. But I fear that it's not that obvious for everyone, and that it is not close to what one would expect.

For instance in my case it wouldn't work. I use different libs that all needs to truncate to 72, but that vary by version (one is generating `$2a$`, another one `$2y$`).
So I should perform string replace on the version prefix and so on...

Yes it's really a mess.

**Comment by patrickfav** [comment]
>For instance in my case it wouldn't work. I use different libs that all needs to truncate to 72, but that vary by version (one is generating $2a$, another one $2y$).
So I should perform string replace on the version prefix and so on...

I'm afraid I don't really understand the problem.

Current state:

* I refactored the verifier to either derive the version from the hash or use a version that is provided. I will keep the API interface as it is for now (passing the verion through verifier)
* The `LongPasswordStrategies` factory class will only accept Versions because I still think it makes the most sense, but anybody can use the implementations without the factory, eg. `new LongPasswordStrategy.TruncateStrategy(72);` so you are free to define whatever you want

**Comment by Indigo744** [comment]
Alright! Works for me 👍 
Thank you!

**Comment by patrickfav** [comment]
Thanks @Indigo744 your input was very valuable for this release. 0.9.0 will be out in a couple of hours.

**Pull request merged**
